/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playmaker.ui;

/**
 *
 * @author carl
 */
public class MainWindow extends javax.swing.JFrame {
    
    public MainWindow() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlayPause = new javax.swing.JButton();
        jpToolChooser = new javax.swing.JPanel();
        tbtnOPlayer = new javax.swing.JToggleButton();
        tbtnDPlayer = new javax.swing.JToggleButton();
        tbtnPath = new javax.swing.JToggleButton();
        tbtnSelect = new javax.swing.JToggleButton();
        btnEmpty = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlayPause.setText("Play");
        btnPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPauseActionPerformed(evt);
            }
        });

        jpToolChooser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tool Chooser", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tbtnOPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O.png"))); // NOI18N
        tbtnOPlayer.setSelected(true);
        tbtnOPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnOPlayerActionPerformed(evt);
            }
        });

        tbtnDPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/X.png"))); // NOI18N
        tbtnDPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnDPlayerActionPerformed(evt);
            }
        });

        tbtnPath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow.png"))); // NOI18N
        tbtnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnPathActionPerformed(evt);
            }
        });

        tbtnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mouse.png"))); // NOI18N
        tbtnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpToolChooserLayout = new javax.swing.GroupLayout(jpToolChooser);
        jpToolChooser.setLayout(jpToolChooserLayout);
        jpToolChooserLayout.setHorizontalGroup(
            jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpToolChooserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbtnOPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbtnDPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbtnPath, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbtnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpToolChooserLayout.setVerticalGroup(
            jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpToolChooserLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpToolChooserLayout.createSequentialGroup()
                        .addGroup(jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtnPath, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tbtnDPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbtnOPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tbtnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnEmpty.setText("Empty");
        btnEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptyActionPerformed(evt);
            }
        });

        btnSave.setText("Save Play");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnLoad.setText("Load Play");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayPause)
                    .addComponent(btnEmpty)
                    .addComponent(btnSave)
                    .addComponent(btnLoad))
                .addGap(52, 52, 52)
                .addComponent(jpToolChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnPlayPause)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmpty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoad))
                    .addComponent(jpToolChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnOPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnOPlayerActionPerformed
        tbtnDPlayer.setSelected(false);
        tbtnPath.setSelected(false);
        tbtnSelect.setSelected(false);
        playArea.setToolType(PlayAreaPanel.ToolType.OFFENSE);
    }//GEN-LAST:event_tbtnOPlayerActionPerformed

    private void tbtnDPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnDPlayerActionPerformed
        tbtnOPlayer.setSelected(false);
        tbtnPath.setSelected(false);
        tbtnSelect.setSelected(false);
        playArea.setToolType(PlayAreaPanel.ToolType.DEFENSE);
    }//GEN-LAST:event_tbtnDPlayerActionPerformed

    private void tbtnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPathActionPerformed
        tbtnOPlayer.setSelected(false);
        tbtnDPlayer.setSelected(false);
        tbtnSelect.setSelected(false);
        playArea.setToolType(PlayAreaPanel.ToolType.PATH);
    }//GEN-LAST:event_tbtnPathActionPerformed

    private void tbtnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSelectActionPerformed
        tbtnOPlayer.setSelected(false);
        tbtnDPlayer.setSelected(false);
        tbtnPath.setSelected(false);
        playArea.setToolType(PlayAreaPanel.ToolType.SELECT);
    }//GEN-LAST:event_tbtnSelectActionPerformed

    private void btnEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptyActionPerformed
        playArea.emptyArea();
    }//GEN-LAST:event_btnEmptyActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPauseActionPerformed
        
    }//GEN-LAST:event_btnPlayPauseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpty;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnPlayPause;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jpToolChooser;
    private javax.swing.JToggleButton tbtnDPlayer;
    private javax.swing.JToggleButton tbtnOPlayer;
    private javax.swing.JToggleButton tbtnPath;
    private javax.swing.JToggleButton tbtnSelect;
    // End of variables declaration//GEN-END:variables
}
