/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playmaker.ui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import playmaker.model.PlayModel;

/**
 *
 * @author carl
 */
public class PlayMakerWindow extends javax.swing.JFrame {
    private PlayModel currentPlay;
    
    public PlayMakerWindow(PlayModel currentPlay) {
        // When the play maker window constructor is called in it's creation,
        // the instances currentPlay is set to the one that is passed. When the
        // fields playAreaPanel, playerDetails, and playController are created they
        // are also have currentPlay passed to them. 
        this.currentPlay = currentPlay;
        
        initComponents();
        // Adds a mouse listner to the play area panel so that it knows when to
        // start and stop drawing the cursor.
        playAreaPanel.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                playAreaPanel.startCursor();
            }
            
            public void mouseExited(MouseEvent evt) {
                playAreaPanel.stopCursor();
            }
            
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpToolChooser = new javax.swing.JPanel();
        tbtnOPlayer = new javax.swing.JToggleButton();
        tbtnDPlayer = new javax.swing.JToggleButton();
        tbtnPath = new javax.swing.JToggleButton();
        tbtnSelect = new javax.swing.JToggleButton();
        playerDetails = new playmaker.ui.PlayerDetails(currentPlay);
        playAreaPanel = new playmaker.ui.PlayAreaPanel(currentPlay);
        lblPlayArea = new javax.swing.JLabel();
        playController = new playmaker.ui.PlayController();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpToolChooser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tool Chooser", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tbtnOPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O.png"))); // NOI18N
        tbtnOPlayer.setSelected(true);
        tbtnOPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnOPlayerActionPerformed(evt);
            }
        });

        tbtnDPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/X.png"))); // NOI18N
        tbtnDPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnDPlayerActionPerformed(evt);
            }
        });

        tbtnPath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow.png"))); // NOI18N
        tbtnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnPathActionPerformed(evt);
            }
        });

        tbtnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mouse.png"))); // NOI18N
        tbtnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpToolChooserLayout = new javax.swing.GroupLayout(jpToolChooser);
        jpToolChooser.setLayout(jpToolChooserLayout);
        jpToolChooserLayout.setHorizontalGroup(
            jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpToolChooserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbtnOPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbtnDPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbtnPath, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbtnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpToolChooserLayout.setVerticalGroup(
            jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpToolChooserLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpToolChooserLayout.createSequentialGroup()
                        .addGroup(jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtnPath, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpToolChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tbtnDPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbtnOPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tbtnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        playerDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        playAreaPanel.setBackground(new java.awt.Color(255, 255, 255));
        playAreaPanel.setBorder(new javax.swing.border.MatteBorder(null));

        lblPlayArea.setText("Play Area");

        javax.swing.GroupLayout playAreaPanelLayout = new javax.swing.GroupLayout(playAreaPanel);
        playAreaPanel.setLayout(playAreaPanelLayout);
        playAreaPanelLayout.setHorizontalGroup(
            playAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayArea)
                .addContainerGap(716, Short.MAX_VALUE))
        );
        playAreaPanelLayout.setVerticalGroup(
            playAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayArea)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        playController.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(playController, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(playAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(playerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jpToolChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playController, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpToolChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnOPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnOPlayerActionPerformed
        tbtnDPlayer.setSelected(false);
        tbtnPath.setSelected(false);
        tbtnSelect.setSelected(false);
        playAreaPanel.setToolType(PlayAreaPanel.ToolType.OFFENSE);
    }//GEN-LAST:event_tbtnOPlayerActionPerformed

    private void tbtnDPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnDPlayerActionPerformed
        tbtnOPlayer.setSelected(false);
        tbtnPath.setSelected(false);
        tbtnSelect.setSelected(false);
        playAreaPanel.setToolType(PlayAreaPanel.ToolType.DEFENSE);
    }//GEN-LAST:event_tbtnDPlayerActionPerformed

    private void tbtnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPathActionPerformed
        tbtnOPlayer.setSelected(false);
        tbtnDPlayer.setSelected(false);
        tbtnSelect.setSelected(false);
        playAreaPanel.setToolType(PlayAreaPanel.ToolType.PATH);
    }//GEN-LAST:event_tbtnPathActionPerformed

    private void tbtnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSelectActionPerformed
        tbtnOPlayer.setSelected(false);
        tbtnDPlayer.setSelected(false);
        tbtnPath.setSelected(false);
        playAreaPanel.setToolType(PlayAreaPanel.ToolType.SELECT);
    }//GEN-LAST:event_tbtnSelectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpToolChooser;
    private javax.swing.JLabel lblPlayArea;
    private playmaker.ui.PlayAreaPanel playAreaPanel;
    private playmaker.ui.PlayController playController;
    private playmaker.ui.PlayerDetails playerDetails;
    private javax.swing.JToggleButton tbtnDPlayer;
    private javax.swing.JToggleButton tbtnOPlayer;
    private javax.swing.JToggleButton tbtnPath;
    private javax.swing.JToggleButton tbtnSelect;
    // End of variables declaration//GEN-END:variables
}