/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playmaker.ui;

/**
 *
 * @author carl
 */
public class PlayerDetails extends javax.swing.JPanel {
    private PlayAreaHandler playerListener;
    /**
     * Creates new form PlayerDetails
     */
    public PlayerDetails() {
        initComponents();
    }
    
    public void setPlayerListener(PlayAreaHandler handler) {
        playerListener = handler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpPlayer = new javax.swing.JLayeredPane();
        jpanScoutView = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnDetailMode = new javax.swing.JButton();
        jpanPlayerDetails = new javax.swing.JPanel();
        jlblHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jcbPos = new javax.swing.JComboBox<>();
        btnMovePlayer = new javax.swing.JButton();
        btnResetplayer = new javax.swing.JButton();
        btnRemovePath = new javax.swing.JButton();
        btnRemovePlayer = new javax.swing.JButton();
        btnScoutMode = new javax.swing.JButton();

        jLabel3.setText("Scout View");

        btnDetailMode.setText("Detail Mode");
        btnDetailMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanScoutViewLayout = new javax.swing.GroupLayout(jpanScoutView);
        jpanScoutView.setLayout(jpanScoutViewLayout);
        jpanScoutViewLayout.setHorizontalGroup(
            jpanScoutViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanScoutViewLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel3)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanScoutViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetailMode)
                .addContainerGap())
        );
        jpanScoutViewLayout.setVerticalGroup(
            jpanScoutViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanScoutViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(148, 148, 148)
                .addComponent(btnDetailMode)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jlblHeader.setText("Player Details");

        jLabel1.setText("Position:");

        jLabel2.setText("Description:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jcbPos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QB", "RB", "WR", "TE", "OL", " " }));

        btnMovePlayer.setText("Move");
        btnMovePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovePlayerActionPerformed(evt);
            }
        });

        btnResetplayer.setText("Reset");
        btnResetplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetplayerActionPerformed(evt);
            }
        });

        btnRemovePath.setText("Remove Path");
        btnRemovePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePathActionPerformed(evt);
            }
        });

        btnRemovePlayer.setText("Remove Player");
        btnRemovePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePlayerActionPerformed(evt);
            }
        });

        btnScoutMode.setText("Scout Mode");
        btnScoutMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoutModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanPlayerDetailsLayout = new javax.swing.GroupLayout(jpanPlayerDetails);
        jpanPlayerDetails.setLayout(jpanPlayerDetailsLayout);
        jpanPlayerDetailsLayout.setHorizontalGroup(
            jpanPlayerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanPlayerDetailsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jlblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72))
            .addGroup(jpanPlayerDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpanPlayerDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanPlayerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpanPlayerDetailsLayout.createSequentialGroup()
                        .addGroup(jpanPlayerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResetplayer)
                            .addComponent(btnRemovePath)
                            .addComponent(btnRemovePlayer)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpanPlayerDetailsLayout.createSequentialGroup()
                        .addComponent(btnMovePlayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnScoutMode)))
                .addContainerGap())
        );
        jpanPlayerDetailsLayout.setVerticalGroup(
            jpanPlayerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanPlayerDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanPlayerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanPlayerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMovePlayer)
                    .addComponent(btnScoutMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetplayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemovePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemovePlayer)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jlpPlayer.setLayer(jpanScoutView, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpPlayer.setLayer(jpanPlayerDetails, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpPlayerLayout = new javax.swing.GroupLayout(jlpPlayer);
        jlpPlayer.setLayout(jlpPlayerLayout);
        jlpPlayerLayout.setHorizontalGroup(
            jlpPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanPlayerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jlpPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jlpPlayerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanScoutView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jlpPlayerLayout.setVerticalGroup(
            jlpPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanPlayerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jlpPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jlpPlayerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanScoutView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpPlayer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpPlayer)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMovePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovePlayerActionPerformed
        
        if (btnMovePlayer.getText() == "Move") {
            this.btnMovePlayer.setText("Pause");
            playerListener.movePlayer();
        } else {
            this.btnMovePlayer.setText("Move");
            playerListener.stopPlayer();
        }
    }//GEN-LAST:event_btnMovePlayerActionPerformed

    private void btnResetplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetplayerActionPerformed
        playerListener.resetPlayer();
    }//GEN-LAST:event_btnResetplayerActionPerformed

    private void btnRemovePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePathActionPerformed
        playerListener.removePlayerPath();
    }//GEN-LAST:event_btnRemovePathActionPerformed

    private void btnRemovePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePlayerActionPerformed
        playerListener.removePlayer();
    }//GEN-LAST:event_btnRemovePlayerActionPerformed

    private void btnScoutModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoutModeActionPerformed
        jpanPlayerDetails.hide();
        jpanScoutView.show();
    }//GEN-LAST:event_btnScoutModeActionPerformed

    private void btnDetailModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailModeActionPerformed
        jpanPlayerDetails.show();
        jpanScoutView.hide();
    }//GEN-LAST:event_btnDetailModeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailMode;
    private javax.swing.JButton btnMovePlayer;
    private javax.swing.JButton btnRemovePath;
    private javax.swing.JButton btnRemovePlayer;
    private javax.swing.JButton btnResetplayer;
    private javax.swing.JButton btnScoutMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jcbPos;
    private javax.swing.JLabel jlblHeader;
    private javax.swing.JLayeredPane jlpPlayer;
    private javax.swing.JPanel jpanPlayerDetails;
    private javax.swing.JPanel jpanScoutView;
    // End of variables declaration//GEN-END:variables
}
