/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playmaker.ui;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.MouseInfo;
import java.awt.geom.Ellipse2D;
import java.util.ArrayList;
import playmaker.model.DPlayer;
import playmaker.model.OPlayer;
import playmaker.model.PlayDetails;
import playmaker.model.Player;

/**
 *
 * @author carl
 */
public class PlayAreaPanel extends javax.swing.JPanel {
    private PlayDetails currentPlay;
     
    private double fieldX = this.getX();
    private double fieldY = this.getY();
    private double fieldW = this.getWidth();
    private double fieldH = this.getHeight();
    
    private ToolType toolType = PlayAreaPanel.ToolType.OFFENSE;
     

    public PlayAreaPanel() {
        currentPlay = new PlayDetails();
        initComponents();
    }
    
    public enum ToolType {
        OFFENSE,
        DEFENSE,
        PATH,
        SELECT
    }
    
    public void setToolType(ToolType toolType) {
        this.toolType = toolType;
    }
    
    public void emptyArea() {
        currentPlay.emptyPlay();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        int mouseX = evt.getX();
        int mouseY = evt.getY();
 
        switch (toolType) {
            case OFFENSE:
                OPlayer tmpOP = new OPlayer(mouseX, mouseY);
                currentPlay.addOPlayer(tmpOP);
                break;
                
            case DEFENSE:
                DPlayer tmpDP = new DPlayer(mouseX, mouseY);
                currentPlay.addDPlayer(tmpDP);
                break;
                
            case PATH:
                currentPlay.addPoint(mouseX, mouseY);
                break;
                
            case SELECT:
                Player clickedPlayer = null;
                
                for(int i = currentPlay.getNumOPlayers()-1; i >= 0 ; i--){
                    OPlayer tmp = currentPlay.getOPlayer(i);
                    if(tmp.pointContainsMe(mouseX, mouseY)){
                        clickedPlayer = tmp;
                        currentPlay.onPlayerClicked(clickedPlayer);
                    break;
                    }
                }
                
                if (clickedPlayer == null) {
                    for(int i = currentPlay.getNumDPlayers()-1; i >= 0 ; i--){
                    DPlayer tmp = currentPlay.getDPlayer(i);
                    if(tmp.pointContainsMe(mouseX, mouseY)){
                        clickedPlayer = tmp;
                        currentPlay.onPlayerClicked(clickedPlayer);
                        break;
                        }
                    }
                }
                break;
                
        }

        repaint();
    }//GEN-LAST:event_formMouseClicked

    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        Graphics2D g2 = (Graphics2D) g;
        /* From https://stackoverflow.com/questions/1439022/get-mouse-position (stack overflow... sorry not sorry)
        PointerInfo mouse = MouseInfo.getPointerInfo();
        Point point = new Point(mouse.getLocation()); 
        double mouseX = point.getX();
        double mouseY = point.getY(); */
        
        currentPlay.drawPlayers(g2);
        currentPlay.drawPaths(g2);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
